name: Release_Tags
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: self-hosted
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Unit Tests
      run: echo Unit Tests

    - name: SAST Scans
      run: echo SAST Scans

    - name: SAST SCA
      run: echo SAST SCA

    - name: Detect Secrets in Source Code
      run: echo Secrets in Source Code

    - name: Produce Artifacts
      run: echo Produce Artifacts